// Code generated by "stringer -type DBType -linecomment"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Mysql-1]
	_ = x[Postgresql-2]
	_ = x[Sqlite-3]
}

const _DBType_name = "mysqlpostgresqlsqlite"

var _DBType_index = [...]uint8{0, 5, 15, 21}

func (i DBType) String() string {
	i -= 1
	if i < 0 || i >= DBType(len(_DBType_index)-1) {
		return "DBType(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DBType_name[_DBType_index[i]:_DBType_index[i+1]]
}
