application: ginLearn
serverPort: 9090
shutDownTimeout: 5

log:
  logPath:
  level: DEBUG
  enableLogConsole: false
  accessMethodRow: false

mysql:
  host: 127.0.0.1
  port: 3306
  user: root
  password: devpwd
  database: demo_shiyanlou
  location: UTC
  tablePrefix:
  singularTable: true
  createBatchSize: 1000
  enableRawSql: true
  maxFreeConnCount: 1
  maxOpenConnCount: 1
  freeMaxLifetime: 30

redis:
  host: 127.0.0.1
  port: 6379
  pwd: A=9q5U776J-6
  maxFreeConnCount: 1
  maxOpenConnCount: 1
  freeMaxLifetime: 30
  database: 0
  connectTimeout: 3
  readTimeout: 3
  writeTimeout: 3
