// Code generated by "stringer -type DBCbWhen"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Before-1]
	_ = x[After-2]
}

const _DBCbWhen_name = "BeforeAfter"

var _DBCbWhen_index = [...]uint8{0, 6, 11}

func (i DBCbWhen) String() string {
	i -= 1
	if i < 0 || i >= DBCbWhen(len(_DBCbWhen_index)-1) {
		return "DBCbWhen(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _DBCbWhen_name[_DBCbWhen_index[i]:_DBCbWhen_index[i+1]]
}
